config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'pages/projects'
  get 'pages/index' 
  root to: 'creatives#index'
  resources :quotes
  resources :contacts
  resources :posts do
    resources :comments
  end
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  resources :users, only: [:index]
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :client
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = current_user.quotes.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = current_user.quotes.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(
        :client, 
        :pages, 
        :images, 
        :hosting, 
        :domain_name, 
        :design, 
        :terms_conditions, 
        :user_registration, 
        :user_registration_details, 
        :budget, 
        :user_id
        )
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :client %>
    <%= f.input :pages %>
    <%= f.input :images %>
    <%= f.input :hosting %>
    <%= f.input :domain_name %>
    <%= f.input :design %>
    <%= f.input :terms_conditions %>
    <%= f.input :user_registration %>
    <%= f.input :user_registration_details %>
    <%= f.input :budget %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-main btn-sm radius" %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Client</th>
      <th>Pages</th>
      <th>Images</th>
      <th>Hosting</th>
      <th>Domain name</th>
      <th>Design</th>
      <th>Terms conditions</th>
      <th>User registration</th>
      <th>User registration details</th>
      <th>Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.client %></td>
        <td><%= quote.pages %></td>
        <td><%= quote.images %></td>
        <td><%= quote.hosting %></td>
        <td><%= quote.domain_name %></td>
        <td><%= quote.design %></td>
        <td><%= quote.terms_conditions %></td>
        <td><%= quote.user_registration %></td>
        <td><%= quote.user_registration_details %></td>
        <td><%= quote.budget %></td>
        <td><%= link_to 'Show', quote, class: "btn-main btn-xs radius"  %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote), class: "btn-edit btn-xs radius"  %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, 
        data: { confirm: 'Are you sure?' }, class: "btn-delete btn-xs radius"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path, class: "btn-main btn-sm radius" %>

app/views/quotes/new.html.erb
<div class='row'>
  <div class= 'col-xs-6 col-xs-offset-3 form'>  
    <h1>New Quote</h1>

    <%= render 'form' %>
    <br />
    <div>
      <%= link_to 'Back', quotes_path, class: "btn-main btn-sm radius pad" %>
    </div>
  </div>
</div>  

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @quote.client %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @quote.pages %>
</p>

<p>
  <strong>Images:</strong>
  <%= @quote.images %>
</p>

<p>
  <strong>Hosting:</strong>
  <%= @quote.hosting %>
</p>

<p>
  <strong>Domain name:</strong>
  <%= @quote.domain_name %>
</p>

<p>
  <strong>Design:</strong>
  <%= @quote.design %>
</p>

<p>
  <strong>Terms conditions:</strong>
  <%= @quote.terms_conditions %>
</p>

<p>
  <strong>User registration:</strong>
  <%= @quote.user_registration %>
</p>

<p>
  <strong>User registration details:</strong>
  <%= @quote.user_registration_details %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @quote.budget %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote), class: "btn-edit btn-xs" %> |
<%= link_to 'Back', quotes_path, class: "btn-main btn-xs" %>